# Generated by Django 5.2.5 on 2025-08-18 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendinguser',
            name='full_name',
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='first_name',
            field=models.CharField(default='John', max_length=50),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='last_name',
            field=models.CharField(default='Doe', max_length=50),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FLCRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('student_organization', models.CharField(max_length=50)),
                ('college_company', models.CharField(max_length=50)),
                ('tour', models.CharField(blank=True, max_length=100)),
                ('tee_shirt_size', models.CharField(blank=True, max_length=10)),
                ('food_allergy', models.CharField(blank=True, max_length=100)),
                ('ada_needs', models.CharField(blank=True, max_length=100)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.pendinguser')),
            ],
        ),
    ]
