# Generated by Django 5.2.5 on 2025-08-19 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_remove_pendinguser_full_name_pendinguser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='flcregistration',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='pendinguser',
            name='verified',
        ),
        migrations.AlterField(
            model_name='flcregistration',
            name='ada_needs',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='flcregistration',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='registrations.pendinguser'),
        ),
        migrations.AlterField(
            model_name='flcregistration',
            name='college_company',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='flcregistration',
            name='first_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='flcregistration',
            name='food_allergy',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='flcregistration',
            name='last_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='flcregistration',
            name='student_organization',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='flcregistration',
            name='tour',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='first_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='last_name',
            field=models.CharField(max_length=120),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
