# Generated by Django 5.2.5 on 2025-08-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_alter_pendinguser_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='college_company',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
