# Generated by Django 5.2.5 on 2025-08-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_pendinguser_college_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
