# Generated by Django 5.2.5 on 2025-08-21 00:17

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_pendinguser_is_validated_pendinguser_validated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLink',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='flcregistration',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
